version: '3'

services:
  app:
    image: vivaconagua/auth-frontend:latest
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      domain_net:
        ipv4_address: ${docker_ip}

networks:
  domain_net:
    external: true
    name: domain_net
